vesrion: 0.1

phases:
  pre_build:
    commands:
      - yarn
    
  build:
    commands:
      - yarn build


artifacts:
  files:
    - index.js
    - index.css
  discard-paths: no
  base-directory: dist
