version: 0.1

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - index.js
    - index.css
  discard-paths: no
  base-directory: dist